unpackaged/main/default/objects/Candidates__c/Candidates__c.object-meta.xml
<CustomObject>
    <label>Candidates</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Candidates__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Candidates__c/fields/Total_Years_experience__c.field-meta.xml
<CustomField>
    <fullName>Total_Years_experience__c</fullName>
    <label>Total Years experience</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/candidatesController.cls
public class candidatesController {
    public candidatesController() {

    }
	@auraenabled
    Public static void createCandidateRecord(string Name){
        Candidates__c candidateRecrod = new Candidates__c();
        candidateRecrod.Name = Name;
        insert candidateRecrod;
    }
    @AuraEnabled
    Public static list<Candidates__c> getData(){
        list<Candidates__c> candidates = [SELECT Id,Name,Phone__c,Primary_Email__c,Skills__c,Total_Years_experience__c From Candidates__c];
        return candidates;
    }
    @AuraEnabled(cacheable=true)
    Public static list<Candidates__c> getCandidatersData(){
        list<Candidates__c> candidates = [SELECT Id,Name,Phone__c,Primary_Email__c,Skills__c,Total_Years_experience__c From Candidates__c];
        return candidates;
    }
    @AuraEnabled(cacheable=true)
    Public static list<Candidates__c> getcandidateRecords(){
        list<Candidates__c> candidates = [SELECT Id,Name,Phone__c,Primary_Email__c,Skills__c,Total_Years_experience__c From Candidates__c];
        return candidates;
    }
}